### ISSUE TITLE
No cambia la categoría ni la fecha del certificado

### ISSUE THREAD

**Issue by jdrodriguez2707** [Laguilavo10/certifications#1]
Hola, revisé la página web y me encantó, pero tengo un problema y es que al intentar cambiar la categoría o entidad y la fecha de algún certificado ya agregado no me la cambia, si no que los deja con la fecha y entidad que les agregué al principio. Todo lo demás me parece que está muy bien.

**Comment by Laguilavo10** [comment]
Hola @jdrodriguez2707 , me alegra que te haya gustado el proyecto, espero que te sea de utilidad. Con respecto a la actualización del certificado ya lo corregi, ahora si deberia funcionar correctamente. Intenta actualizarlo y me cuentas que tal.

**Comment by Laguilavo10** [comment]
> Hola, revisé la página web y me encantó, pero tengo un problema y es que al intentar cambiar la categoría o entidad y la fecha de algún certificado ya agregado no me la cambia, si no que los deja con la fecha y entidad que les agregué al principio. Todo lo demás me parece que está muy bien.

Hola @jdrodriguez2707 , me alegra que te haya gustado el proyecto, espero que te sea de utilidad. Con respecto a la actualización del certificado ya lo corregi, ahora si deberia funcionar correctamente. Intenta actualizarlo y me cuentas que tal.

**Comment by jdrodriguez2707** [comment]
Listo, ahora me funciona correctamente. Muchas gracias. Algo que me gustaría es que cuando se suban los certificados haya una forma más rápida de acceder a la página principal para visualizarlos y no tener que ir al Dashboard para presionar el botón, pero es un tema menor. Sin más, te deseo muchos éxitos con este y futuros proyectos 💪🏼.
